CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE category {
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(128),
code VARCHAR(16),
}


CREATE TABLE lot {
id INT AUTO_INCREMENT PRIMARY KEY,
createdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
description VARCHAR(255),
startprice MEDIUMINT NOT NULL,
enddate TIMESTAMP NOT NULL,
bidstep MEDIUMINT NOT NULL,
monteiner_id SMALLINT NOT NULL,
winner_id SMALLINT NOT NULL,
category_id SMALLINT NOT NULL,
}

CREATE TABLE bit {
id INT AUTO_INCREMENT PRIMARY KEY,
createdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
bid MEDIUMINT NOT NULL,
user_id SMALLINT NOT NULL,
lot_id SMALLINT NOT NULL,
}

CREATE TABLE user {
creatuser TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(128) NOT NULL UNIQUE,
name VARCHAR(128) NOT NULL UNIQUE,
password CHAR(64) NOT NULL,
contact CHAR(255) NOT NULL,
lot_id SMALLINT,
bit_id SMALLINT,

}
