CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
CREATE TABLE bit {
id INT AUTO_INCREMENT PRIMARY KEY,
createdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
description VARCHAR(255),



}
