DROP DATABASE IF EXISTS yeticave;
CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE yeticave;

CREATE TABLE category (
id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(128) NOT NULL,
code VARCHAR(16) NOT NULL
);

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
creatuser TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(128) NOT NULL UNIQUE,
name VARCHAR(128) NOT NULL UNIQUE,
password CHAR(64) NOT NULL,
contact TEXT
);

CREATE TABLE lot (
id INT AUTO_INCREMENT PRIMARY KEY,
createdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
description VARCHAR(255),
title VARCHAR(255),
img VARCHAR(255),
startprice MEDIUMINT NOT NULL,
enddate DATE NOT NULL,
bidstep MEDIUMINT NOT NULL,
monteiner_id INT NOT NULL,
winner_id INT,
category_id INT NOT NULL,
FOREIGN KEY (monteiner_id) REFERENCES users(id),
FOREIGN KEY (winner_id) REFERENCES users(id),
FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE bit (
id INT AUTO_INCREMENT PRIMARY KEY,
createdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
bid INT NOT NULL,
user_id INT NOT NULL,
lot_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (lot_id) REFERENCES lot(id)
);
